Born of .travis.yml
annkupriyanova/wiki-framework pull request #9
Opened 2018-12-13 22:08 UTC by baevpetr

Initialization of Travis-CI.
@annkupriyanova have to make following steps:
- Go to [Travis-ci.com](url) and Sign up with GitHub.
- Accept the Authorization of Travis CI. You’ll be redirected to GitHub.
- Click the green Activate button, and select the repositories you want to use with Travis CI.

2018-12-14 20:25 UTC, cdeler requested changes

2018-12-14 20:25 UTC, cdeler commented on .travis.yml
> +dist: xenial      # 12.04 Precise default
Why not 18.04?

2018-12-14 20:25 UTC, cdeler commented on .travis.yml
> +   pwd #- python -m pytest -v
Please remove unused comments

+ why did you comment the test execution out?

2018-12-14 20:26 UTC, cdeler commented
Also good idea (for me) is to squash all commits with minor changes into the single one

2018-12-14 21:50 UTC, baevpetr commented on .travis.yml
> +dist: xenial      # 12.04 Precise default
The reason is that Travis doesn't support 18 version. I assume that this is a question with a hint. Then there's an opportunity to use 18.04 with Docker.

2018-12-14 21:52 UTC, baevpetr commented
My fault. Forgot to use `--amend`...

2018-12-14 22:21 UTC, baevpetr commented on .travis.yml
> +   pwd #- python -m pytest -v
Must be `script`. But there are no tests) I will fix.

2018-12-19 13:52 UTC, annkupriyanova reviewed
I've fulfilled the instruction and activated Travis CI for this repository. Check it.

2018-12-20 22:44 UTC, baevpetr commented
I can't see your account. So approve PR if it ok for you. And I'm just waiting further commands\clarifications from @cdeler about version of Ubuntu and usage of Docker.

2018-12-21 19:54 UTC, cdeler approved these changes

2018-12-21 19:55 UTC, cdeler commented
Just resolve the conflict :-)

2018-12-22 16:59 UTC, annkupriyanova approved these changes

2023-08-11 12:59 UTC, closed without merging